//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logeo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbCorrespondenciaEntities : DbContext
    {
        public dbCorrespondenciaEntities()
            : base("name=dbCorrespondenciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tabla> tabla { get; set; }
        public virtual DbSet<tblCiudadDpto> tblCiudadDpto { get; set; }
        public virtual DbSet<tblDependencia> tblDependencia { get; set; }
        public virtual DbSet<tblDocEntrada> tblDocEntrada { get; set; }
        public virtual DbSet<tblDocSalida> tblDocSalida { get; set; }
        public virtual DbSet<tblDocumento> tblDocumento { get; set; }
        public virtual DbSet<tblUsuarioCorrespondencia> tblUsuarioCorrespondencia { get; set; }
    }
}
