//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logeo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocEntrada
    {
        public int radicado { get; set; }
        public System.DateTime fechaEntrada { get; set; }
        public int idRemitente { get; set; }
    
        public virtual tblDocumento tblDocumento { get; set; }
        public virtual tblUsuarioCorrespondencia tblUsuarioCorrespondencia { get; set; }
    }
}
