//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logeo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuarioCorrespondencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsuarioCorrespondencia()
        {
            this.tblDocEntrada = new HashSet<tblDocEntrada>();
            this.tblDocSalida = new HashSet<tblDocSalida>();
        }
    
        public int id { get; set; }
        public string nombreRazonSocial { get; set; }
        public string direccion { get; set; }
        public int idCiudad { get; set; }
    
        public virtual tblCiudadDpto tblCiudadDpto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocEntrada> tblDocEntrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocSalida> tblDocSalida { get; set; }
    }
}
